### ISSUE TITLE
détail des TP Post-introduction Galaxy

### ISSUE THREAD

**Issue by drosofff** [ARTbio/AnalyseGenome#1]
@slecrom est ce que tu pourrais mettre un lien vers le "poly" des analyses galaxy faites après ma journée ?
L'idée de familiariser avec Galaxy tout en avançant sur ce qu'il y a à faire après.

**Comment by slecrom** [comment]
Bonjour @drosofff 
Tu peux accéder au poly du TP de l'année dernière à cette adresse : https://slecrom.github.io/AG2021/
Je vais créer une version 2022 pour prendre en compte les modifications et mises à jour de Galaxy de cette année.
Bonne journée,
Stéphane

**Comment by drosofff** [comment]
👍
