### ISSUE TITLE
Tutoriel sur la création d'un projet dans GCE ?

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#10]
Je me demande si ce ne serait pas une bonne idée de les faire travailler dans un projet pour le cours et d'y rattacher le coupon qu'ils ont obtenu ? Qu'en penses-tu ?

**Comment by drosofff** [comment]
C’est obligatoire. Il ont forcément un projet rattaché au coupon si il veulent lancer une VM !
