### ISSUE TITLE
Création d'une VM de secours

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#11]
Penses-tu que tu puisses créer une VM de secours comme l'année dernière dans l'état dans lequel elle devrait être à la fin de ta session ? Cela permettrait de rattraper les éventuels problèmes.

**Comment by drosofff** [comment]
Oui... Je peux faire ça. Ca me fera un entrainnement à la gestion des droits d'accès de Google Cloud, une véritable usine à gaz.

 Mais cela ne servira pas, j'ai grande confiance ;-)

**Comment by slecrom** [comment]
Ok. Mais moi je suis un grand inquiet ;-)

**Comment by slecrom** [comment]
Merci @drosofff pour la création de la VM de secours et le tutoriel. Je viens de la tester et tout fonctionne.

J'ai encore une question, comment fait-on pour extraire 1 dataset d'une collection ? Si par exemple, je voulais sortir SF2 de la collection SF pour faire des tests dessus ?

**Comment by drosofff** [comment]
>  Je viens de la tester et tout fonctionne.

Waou ! Je ne pensais pas que ça marcherait du premier coup, j'en ai chi$`% avec la documentation vaseuse sur le partage des VM. Là, franchement, +1 pour Amazon !

> J'ai encore une question, comment fait-on pour extraire 1 dataset d'une collection ? Si par exemple, je voulais sortir SF2 de la collection SF pour faire des tests dessus ?

En fait, tu n'as plus besoin d'extraire un dataset de sa collection pour travailler dessus. Dans l'outil, tu utilises l'icône de folder à droite de la boite de sélection d'inputs (en mode fichier seul), et tu sélectionnes le dataset de ton choix.

<img width="652" alt="Capture d’écran 2022-11-24 à 11 24 03" src="https://user-images.githubusercontent.com/11705625/203762602-37a0f352-f546-484e-b0ae-07a68255bef3.png">


Cela dit, il existe bel et bien un outil qui fait cela, installé par défaut dans Galaxy, et qui s'appelle "extract dataset" (dans le menu "Collection opérations", résurgence de temps où la procédure ci-dessus n'était pas possible (il y a bien 3-4 ans maintenant)

**Comment by drosofff** [comment]
Pour la VM, ça donne presque envie de démarrer le training avec !!! Ca permettrait de se concentrer sur l'utilisation de Galaxy ;-)

D'un autre coté, j'adore utiliser GCE et bricoler avec des VM... Mais j'ai jamais eu l'impression que ça passionnait les étudiants... Ya une courbe d'acculturation un peu trop raide je pense.

**Comment by slecrom** [comment]
Je trouve que leur montrer l'utilisation d'une VM c'est quand même utile. Ils sont abonnés pour leurs musiques, leurs séries, leurs téléphones… Pourquoi pas aussi leurs serveurs ? J'aimerais bien que le réflexe, je me commande ma machine super puissante dès que j'arrive dans un labo disparaisse un peu.

**Comment by slecrom** [comment]
Si on veut copier un élément de la collection dans un autre historique, il faut donc l'extraire avant ?

**Comment by drosofff** [comment]
Ce n'est pas nécessaire non plus:

- tu montres les datasets cachés en appuyant sur l'oeil barré, pour les dataset cachés (qui sont les éléments de collection), tu fais "unhide". et quand ils sont unhided, les datasets sont accessibles dans le menu de copie !

C'est juste que si t'as pas bien compris ce qu'est une collection, ça devient compliqué quand tu as unhidés les datasets qui la composent... Remarque que tu peux toujours les "re-hider" ;-)

Moi je n'aime pas extraire les datasets d'une collection, car c'est une vraie opération de copie, tu dupliques tes données et l'espace qu'elles occupent. Dans, l'exemple ci-dessus, le fait de copier un dataset unhidé prend 0 octet sur le disque !
