### ISSUE TITLE
Manipulation de la matrice d'expression

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#13]
À la fin de l'étape "featurecounts" j'obtiens 6 fichiers différents. J'aurais bien aimé créer une matrice d'expression qui les rassemble pour faire 2-3 manips dessus comme une distribution des comptages, calculer le nombre de lignes à 0.

En ligne de commande j'aurais fait un paste puis un cut pour obtenir la matrice. Puis je serai passé dans R pour faire un summary. 

On peut faire la même chose dans Galaxy ?

**Comment by drosofff** [comment]
Sure ! :-)

**Comment by drosofff** [comment]
@slecrom here is a [url for a workflow](https://raw.githubusercontent.com/ARTbio/AnalyseGenome/main/Exercises/Galaxy-Workflow-Table_and_statistics.ga) that you can use in the "upload workflow" menu (workflow menu) and is doing what you want, starting from the two collection counts generated by FeatureCounts using WT and SF alignment collection.

**Comment by slecrom** [comment]
Merci @drosofff je vais tester ça. Tu ne voudrais pas leur faire tester ce workflow demain après-midi ? Je me rends compte que c'est un peu juste niveau timing, si tu n'as pas le temps ce n'est pas grave.

**Comment by drosofff** [comment]
Cela implique d'aller jusqu'au featurecounts donc alignement, et comptage. c'est un peu long et ça mord pas mal sur ton programme ! 
mais en revanche, ce que je peux faire c'est leur faire installer les deux outils ! Après, le workflow c'est one click, et ça marchera

**Comment by slecrom** [comment]
On pourrait partir des fichiers de feature counts déjà calculés ? Comme tu veux.
