### ISSUE TITLE
Outils "invisibles" après la reprise de la VM 

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#14]
Je voulais reprendre des tests sur la VM que j'avais suspendue hier et FastQC n'apparaissait plus dans la barre de recherche. Les sections "analyse des génomes" et "SAMTOOLS" avaient disparu. Pourtant, dans la partie admin Fastqc était bien là.

Un redémarrage du serveur galaxy "galaxyctl restart" a réglé le problème. Mais peut-être faut-il le faire systématiquement ?

<img width="288" alt="Capture d’écran 2022-11-25 à 17 35 48" src="https://user-images.githubusercontent.com/8030105/204027360-96304b39-d181-4ce3-8297-a1e75dd95597.png">
<img width="288" alt="Capture d’écran 2022-11-25 à 17 36 04" src="https://user-images.githubusercontent.com/8030105/204027367-18917cfb-536b-414b-8db7-4972b338d476.png">
<img width="1177" alt="Capture d’écran 2022-11-25 à 17 36 25" src="https://user-images.githubusercontent.com/8030105/204027370-b14adb69-8232-4dab-822b-e81e8e1384a2.png">

**Comment by drosofff** [comment]
La barre de recherche des outils de Galaxy est un vieux problème qui avance lentement. Avec la version 22.05 il m'a semblé qu'il y avait du mieux mais je n'ai pas expérimenté les détails: en particulier, il m'a semblé que peut-être un simple rechargement de la page Galaxy en appuyant sur le logo ou en utilisant la touche rechargement du browser pouvait suffir à faire réapparaitre l'outil. Mais je ne suis pas sûr.

En tout état de cause, c'est un problème de cache web et le `galaxyclt restart` reste une manière sure de retrouver les outils "perdus"
