### ISSUE TITLE
Galaxy tool list

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#17]
Hi @drosofff 
Where can I find the list of tools used last year for the "analyse des génomes" Galaxy server?
Thank you

**Comment by drosofff** [comment]
In this repo !

https://github.com/ARTbio/AnalyseGenome/blob/main/GalaxyServer/bg_tools.yml

I will try to improve this part this year, taking benefit of the adoption of mamba as package solver in conda. Since it is superfast now, I hope that we can skip the caching of the tool conda environments...

**Comment by slecrom** [comment]
Thank you. Here the list of tools I will use this year for the practical.

`tools:

- name: data_manager_fetch_genome_dbkeys_all_fasta
  owner: devteam
  tool_panel_section_label: null
  tool_shed_url: https://toolshed.g2.bx.psu.edu/

- name: data_manager_bowtie_index_builder
  owner: iuc
  tool_panel_section_label: null
  tool_shed_url: https://toolshed.g2.bx.psu.edu/

# General tools for the practical

- name: regex_find_and_replace
  owner: galaxyp
  tool_panel_section_id: ag2023
  tool_panel_section_label: AG 2023
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: cherry_pick_fasta
  owner: artbio
  tool_panel_section_id: ag2023
  tool_panel_section_label: AG 2023
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fastqc
  owner: devteam
  tool_panel_section_id: ag2023
  tool_panel_section_label: AG 2023
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: rseqc
  owner: nilesh
  tool_panel_section_id: ag2023
  tool_panel_section_label: AG 2023
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: text_processing
  owner: bgruening
  tool_panel_section_id: ag2023
  tool_panel_section_label: AG 2023
  tool_shed_url: toolshed.g2.bx.psu.edu

# Tools for small RNA analysis

- name: yac_clipper
  owner: artbio
  tool_panel_section_id: srna
  tool_panel_section_label: Small RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: sr_bowtie
  owner: artbio
  tool_panel_section_id: srna
  tool_panel_section_label: Small RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: small_rna_maps
  owner: artbio
  tool_panel_section_id: srna
  tool_panel_section_label: Small RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: weblogo3
  owner: devteam
  tool_panel_section_id: srna
  tool_panel_section_label: Small RNA
  tool_shed_url: toolshed.g2.bx.psu.edu

# Tools for RNA-seq analysis

- name: bowtie_wrappers
  owner: devteam
  tool_panel_section_id: rna
  tool_panel_section_label: RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: featurecounts
  owner: iuc
  tool_panel_section_id: rna
  tool_panel_section_label: RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: deseq2
  owner: iuc
  tool_panel_section_id: rna
  tool_panel_section_label: RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: volcano_plot
  owner: iuc
  tool_panel_section_id: rna
  tool_panel_section_label: RNA
  tool_shed_url: toolshed.g2.bx.psu.edu
  
# HTS data manipulation

- name: sequence_format_converter
  owner: artbio
  tool_panel_section_id: hts_data
  tool_panel_section_label: HTS data manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: trimmomatic
  owner: pjbriggs
  tool_panel_section_id: hts_data
  tool_panel_section_label: HTS data manipulation
  tool_shed_url: toolshed.g2.bx.psu.edu

# Samtools

- name: samtools_sort
  owner: devteam
  tool_panel_section_id: samtools
  tool_panel_section_label: Samtools
  tool_shed_url: https://toolshed.g2.bx.psu.edu/
- name: samtools_stats
  owner: devteam
  tool_panel_section_id: samtools
  tool_panel_section_label: Samtools
  tool_shed_url: https://toolshed.g2.bx.psu.edu/
- name: samtools_view
  owner: iuc
  tool_panel_section_id: samtools
  tool_panel_section_label: Samtools
  tool_shed_url: https://toolshed.g2.bx.psu.edu/
- name: samtool_filter2
  owner: devteam
  tool_panel_section_id: samtools
  tool_panel_section_label: Samtools
  tool_shed_url: https://toolshed.g2.bx.psu.edu/
`

**Comment by slecrom** [comment]
Bonjour @drosofff 

Est-ce que la suite [BedTools](https://bedtools.readthedocs.io/en/latest/) est disponible dans Galaxy ? J'imagine que oui. Penses-tu que ce soit possible de l'ajouter à la liste des outils de la VM ? Peut-être dans une section dédiée ou dans la section "Samtools" renommée "Sam et Bed Tools" ?

Je te remercie
Bon après-midi

**Comment by drosofff** [comment]
@slecrom , va pour une section bedtools !
