### ISSUE TITLE
Blocage dans l'installation de l'instance "bare-galaxy"

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#2]
Bonjour Christophe,

J'ai voulu me remettre dans le bain du TP en faisant une installation d'un serveur Galaxy Minimal en suivant le tutoriel disponible ici : https://artbio.github.io/startbio/Run-Galaxy/bare-galaxy-google/
Mais quand j'ai lancé le script de démarrage du serveur : sh run.sh, le processus est bloqué à l'étape ci-dessous :
galaxy.jobs.handler DEBUG 2022-11-10 13:05:41,407 [pN:main.web.1,p:3706,w:1,m:0,tN:MainThread] Loaded job runners plugins: local

Sais-tu d'où cela peut provenir ? J'attache le log complet de la console de la VM GCE.

Je te remercie
Bon après-midi,
Stéphane
[221110_HistoriqueInstallGalaxy.txt](https://github.com/ARTbio/AnalyseGenome/files/9981141/221110_HistoriqueInstallGalaxy.txt)

**Comment by drosofff** [comment]
AH, je n'avais pas vu @slecrom 
```
serving on http://127.0.0.1:80
```
c'est le `127.0.0.1` qui posait un problème. Cela doit être à la place: `0.0.0.0` (remplacer `localhost` par `0.0.0.0`)
