### ISSUE TITLE
Sub-sample a Fastq file

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#26]
Bonjour @drosofff 

Je voudrais sous-échantillonner un fichier Fastq pour ne garder que 10 millions de lectures afin de faire des tests des paramètres d'alignement avec les étudiants. Sur mississippi j'ai trouvé l'outil "Sample (ngs-tools) (Galaxy Version 1.0.0)" mais quand je le lance j'ai un message d'erreur : 
`/home/galaxy/galaxy/database/jobs/000/108/108806/tool_script.sh: line 9: ngs-tools: command not found`

Peux-tu ajouter l'outil manquant pour que cela fonctionne ? Ou alors as-tu d'autres suggestions d'outils plus adaptés ?

Je te remercie
Bonne journée,
Stéphane

**Comment by drosofff** [comment]
Hooooo là là oui, c'est un vieil outil qui ne marche plus (dernière maj 2013) et qui ne devrait pas se trouver là.
Je le retire immédiatement !

dans la suite seqtk, il y a l'outil seqtk_sample qui fonctionne correctement !

**Comment by drosofff** [comment]
@slecrom Je l'ajoute dans le build de la VM AG2023.

By the way, j'ai terminé la mise à jour complète sur le repo startbio (https://artbio.github.io/startbio/AnalyseGenomes_2023/outline/)

Il me reste à checker que ta mise à jour https://slecrom.github.io/AG2023/ est entièrement compatible avec les liens de téléchargement de fichiers. Je présume pour le moment que les données primaires sont les même qu'en 2022 ?

**Comment by slecrom** [comment]
Merci @drosofff  En fait, je n'ai pas posté ma demande au bon endroit, car c'est sûr le serveur Mississippi que j'ai besoin de l'outil de sampling. Sur la machine du cours, les étudiants n'en auront pas besoin.

Pour les données, je suis en train de terminer les tests. On change de dataset cette année et je viens de me rendre compte que le repository sur dryad est 8x plus lent que si les données sont sur psilo. J'essaye de finir ça en début de semaine.

**Comment by drosofff** [comment]
> Merci @drosofff En fait, je n'ai pas posté ma demande au bon endroit, car c'est sûr le serveur Mississippi que j'ai besoin de l'outil de sampling. Sur la machine du cours, les étudiants n'en auront pas besoin.

Bon... Abondance de bien ne nuit pas, ils l'ont aussi sur leur deploiement Google du coup...
et l'outil seqkt_sample est bien sur Mississippi[2] !

> Pour les données, je suis en train de terminer les tests. On change de dataset cette année et je viens de me rendre compte que le repository sur dryad est 8x plus lent que si les données sont sur psilo. J'essaye de finir ça en début de semaine.

Ca fait pas de pub à PSILO, mais... Mettez les datasets sur [Zenodo](https://zenodo.org/) ! C'est le repo officiel pour le Galaxy training Network !
Et en prime, tu auras un DOI ! Si je n'avais pas PSILO sous la main, j'irai directement sur Zenodo, c'est sûr !

Tiens moi au courant quand tu as mis à jour les datasets, car la semaine qui vient j'aurai très peu de temps à consacrer à l'AG2023...

Pourra tu checker que l'image de secours fonctionne pour toi: https://artbio.github.io/startbio/AnalyseGenomes_2023/emergency_image/#in-case-of-big-big-troubles-with-your-vm-instance
