### ISSUE TITLE
Publication of the AdG documentation - year 2022 is pending !

### ISSUE THREAD

**Issue by drosofff** [ARTbio/AnalyseGenome#3]
See a preview here @slecrom :

## https://artbio.github.io/startbio/AnalyseGenomes_2022/outline/

**Comment by drosofff** [comment]
@slecrom je suis d'accord avec ton découpage, c'est comme cela que je voyais le timing.
Ce matin je n'avais pas encore poussé la nouvelle version de la partie `upload data` et prepare `reference genomes`... c'est fait maintenant et tu verras que c'est pas mal simplifié par rapport à l'année dernière.

Si j'ai bien compris, ce que tu proposes de faire c'est de mettre le use case "conversion de format" et l'application workflow qui en découle à la fin. Oui pourquoi pas.
J'ai même envisagé de mettre le upload data et prepare reference génome immédiatement après le déploiement de Galaxy et pendant l'installation des outils (en mettant les data manager en début d'installation).

Mais globalement, je suis moins pessimiste que toi: j'ai l'impression que quelque soit l'ordre, ça passera en 4 heures.
De tout façon je ferai un timing précis dans quelques jours, en essayant de trouver un jeune sparing partenaire un peu bleu.


> ? Comment arrêter et lancer Galaxy, je le suis connecté au screen et fait un Ctrl+D mais pour le relancer je n'ai pas trouvé ?

Ctrl-A + D plutôt... tant que la session est vivante, tu peux la voir en faisant `screen -ls` et en la réattachant par `screen -r galaxyscreen`. Le process galaxy la maintient en vie.
En revanche si tu kill galaxy après la toute première installation (deploy_galaxy.sh), cela **termine** le screen galaxyscreen.

Tu peux alors t'en apercevoir en faisant un `screen -ls`

Même comportement si tu **arrêtes** la VM. En le redémarrant tu verras que tous les screens ont été tués (ce qui est inévitable).

A partir de là je viens de rajouter  un petit script de redémarrage `fresh-run.sh` qu'il suffira d'appeller pour recreer un screen et relancer le serveur galaxy.

La bonne nouvelle finalement c'est que c'est année, la fonctionnalité "suspendre la VM" est disponible. Donc, en fin de journée, tu peux simplement suspendre la vm et la relancer le lendemain, sans que l'environnement général n'est été affecté. Donc tout ces petits soucis de comprehension des shells linux, devraient passer au deuxième plan (même si AMHA tout étudiant de M2 devrait au moins apprendre cela qu'il fasse de la bioinfo ou pas).

> ? Il y a une différence dans le nombre de séquences clippées en ligne de commande (8125019) et via Galaxy (8,166,919 sequences) ?

Ah ah ! Excellent ! 
Je me demande si ils le verront 😄 Je crois que je vais continuer à ne rien dire...

La réponse ne peut se trouver qu'en comparant les codes sources: `yac.py`admet un mismatch dans les 7 premiers nucléotides de l'adaptateur, alors que notre expression régulière impose une stricte identité sur ces 7 nucleotides.
Bon... la différence n'est que de 0.05% après tout...

C'est un joli use case qui montre qu'il est difficile de faire de l'analyse à top niveau sans savoir lire les codes, et aussi qu'un code non-ouvert c'est un vrai problème dans ce genre de situation...
En même je pense qu'un généticien comparerait les phénotypes des fichiers et finirait pas comprendre que c'est le gène du clipping qui est muté 😆 

C'est peut être aussi l'occasion de leur montrer qu'on peut très bien faire tourner le code d'un outil galaxy en ligne de commande... si on est maso 😄

**Comment by slecrom** [comment]
@drosofff peux-tu me dire où se trouve le fichier fresh-run.sh pour que je puisse le tester ? Merci

**Comment by slecrom** [comment]
Ok. Sinon comment lance-t-on le serveur galaxy dans un screen ? J'ai lancé le sh galaxy/run.sh mais dans un screen ce serait plus propre. Intuitivement je dirais :
screen -S galaxy
sh galaxy/run.sh

**Comment by drosofff** [comment]
Oui, si le screen `galaxy` n'existe pas déjà, sinon screen te diras que ce screen -S n'est pas possible.

et 

`sh /root/galaxy/run.sh` est mieux car marchera où que tu te trouves

**Comment by slecrom** [comment]
Je viens de tester le chargement des données et cela va très vite. Je suis en train de tester la décompression et l'interface a changé depuis ton tutoriel. Je te mets la version actuelle ci-dessous.
![Capture d’écran 2022-11-15 à 17 38 21](https://user-images.githubusercontent.com/8030105/201976141-da87431d-8859-4f72-ba71-4ab30846fad2.png)

**Comment by drosofff** [comment]
c'est effectivement fait exprès pour que les étudiants l'installe. Mais ce qu'ils sont sensés installer est celui de galaxyp, pas de jjohnson.

Tu n'a pas vu ? Un problème de plan ? (j'ai remanié un peu partout mais pas testé la consistence linéaire partout...)

Je pense que le jjohson n'a pas survécu au passage à python3...

**Comment by slecrom** [comment]
Tu as raison, je me suis mélangé les versions. Par contre, j'ai dû louper l'endroit où tu l'installes. Dans quelle partie est-ce ? 

J'ai une question. Est-ce que l'on peut renommer une collection quand les outils sont lancés ? J'ai essayé en cliquant sur le crayon mais je n'ai pas accès au nom de l'étape.

![Uploading Capture d’écran 2022-11-16 à 14.35.40.png…]()

**Comment by slecrom** [comment]
![Capture d’écran 2022-11-16 à 14 35 40](https://user-images.githubusercontent.com/8030105/202194901-cacb61a3-8ece-4a38-909c-53275721782d.png)

**Comment by slecrom** [comment]
Je crois que l'outil "Use the 🔧 Select lines that match an expression (Galaxy Version 1.0.3)" n'est pas installé. En tout cas, je ne le trouve pas. Peux-tu me dire quel est le nom de l'outil dans le ToolShed pour que je l'installe ? Merci.

**Comment by slecrom** [comment]
Je suis toujours dans la préparation des génomes et je rencontre une erreur avec la déclaration du génome de référence.

An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/data_manager_fetch_genome_all_fasta_dbkey/0.0.4.
An error occurred with this dataset:
format data_manager_json database [?](http://34.65.233.217/datasets/error#)
exec_after_process hook failed

![Capture d’écran 2022-11-16 à 14 55 36](https://user-images.githubusercontent.com/8030105/202199321-343f2866-e31a-467f-a2b8-ecc4fdd3e170.png)

**Comment by drosofff** [comment]
> "Use the 🔧 Select lines that match an expression (Galaxy Version 1.0.3)"

Est ce que tu peux me dire sur quelle section du training tu es ? j'ai du mal à te suivre...

**Comment by drosofff** [comment]
> An error occurred while running the tool  toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/data_manager_fetch_genome_all_fasta_dbkey/0.0.4.

Tu es sûr que tu n'a pas _déjà_ déclaré cette dbkey auparavant ?

**Comment by slecrom** [comment]
Je suis là : https://artbio.github.io/startbio/AnalyseGenomes_2022/Preparing_reference/#b-declare-the-dmel-main-chromosome-r618-dataset-as-a-reference-to-galaxy

En fait j'ai l'impression que le génome de référence existe déjà. Si c'est le cas j'aurais ce message d'erreur ?
![Capture d’écran 2022-11-16 à 15 00 29](https://user-images.githubusercontent.com/8030105/202200689-7cb58ec6-29bc-44f4-a66b-3977230f8927.png)
![Capture d’écran 2022-11-16 à 15 00 44](https://user-images.githubusercontent.com/8030105/202200701-75c45437-fef7-4044-aa39-66d424189a80.png)

Mais je n'ai pas souvenir de l'avoir fait !

**Comment by slecrom** [comment]
Est-ce que je peux les effacer pour recommencer proprement ? Car je ne suis pas sûr que ce soit le génome avec les fasta nettoyés qui soit indexé.

**Comment by drosofff** [comment]
Alors... c'est bien cela, tu as déjà fait un index dmel pour le use case "bowtie avec galaxy"... (mais les étudiants ne le feront plus car j'ai modifié hier ce use case).
Maintenant, ne t'embête pas à effacer un génome de référence (c'est toujours casse-gueule), donne à celui là une autre dbkey, du genre dmel-main-r6.18, et en voiture simone !

**Comment by slecrom** [comment]
Merci 👍

**Comment by slecrom** [comment]
Pourrais-tu déplacer la partie sur les aides à la commande screen en annexe ? Je les ai pas mal utilisées cette semaine et comme je ne suis pas un pro, j'ai eu du mal à me le rappeler. Et retrouver où dans la doc cela se trouvait c'est compliqué. Je suis passé par l'outil de recherche, mais ce n'est pas optimal je trouve.

Je te remercie
Bonne journée,
Stéphane
