### ISSUE TITLE
Galaxy tool installation error

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#31]
Bonjour @drosofff 

Depuis hier 2 étudiants m'ont fait remonter une erreur dans l'installation des outils dans Galaxy : 
```
bioblend.ConnectionError: GET: error 403: b'{"err_msg": "Provided API key is not valid.", "err_code": 403001}', 0 attempts left: {"err_msg": "Provided API key is not valid.", "err_code": 403001}
```
Est-ce que c'est un problème de collage de la clef API du serveur ?

**Comment by drosofff** [comment]
Soit ça, soit ce que j'évoquais ce matin:

Si il ont créé leur compte galaxy sans suivre l'instruction d'utiliser le mail admin@galaxy.org, alors ils ont bien l'impression d'avoir un compte, il peuvent très bien générer une clé API... mais comme il ne seront de toutes façons pas admin, la clé API ne servira à rien !

Pour le tester c'est simple: il faut qu'ils créé un deuxième compte sur galaxy, en utilisant admin@galaxy.org. S'ils l'avaient déjà fait, Galaxy leur dira que l'ID est déjà pris... sinon mon hypothèse est la bonne... à partir de là, créer une nouvelle API key, et ça marchera...
