### ISSUE TITLE
Stop Galaxy workflow

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#33]
Bonjour @drosofff 

Sais-tu comment arrêter des workflow qui sont lancés ? Julie a lancé plusieurs fois son workflow et je me demande si cela ne va pas bloquer son serveur Galaxy.

Je te remercie

**Comment by drosofff** [comment]
Cela étant dit sur slack ;-)... non, tu ne peux pas "bloquer" Galaxy avec plein de workflow.
Simplement, il va y avoir une file d'attente et il va falloir attendre son tour. Galaxy n'est pas bloqué, mais toi oui :-)
