### ISSUE TITLE
Bowtie index builder error

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#37]
I followed the STARTbio tutorial and when I tried to perform the Bowtie index of the genome (https://artbio.github.io/startbio/AnalyseGenomes_2023/Preparing_reference/#2-index-dmel-r654-for-bowtie), I got an error message : "Conda dependency seemingly installed but failed to build job environment."

![Capture d’écran 2024-11-04 à 15 41 02](https://github.com/user-attachments/assets/893d577c-402f-450a-8a13-e68055cf5372)

**Comment by drosofff** [comment]
Oui, je reproduis le même problème @slecrom. Il semblerait que l'environnement conda de ces instances galaxy ne soit pas dans une forme étincelante. Je parie pour des problèmes de droits ou de versions, car si tu regardes bien, dans le script d'installation des outils, je manipule conda... Je vais regarder.

PS. Je suis à deux doigts de switcher sur une installation avec [galaxyXpand](https://github.com/ARTbio/galaxyXpand) (le successeur de GalaxyKickStart). Ca évite quand même la plupart de ces tête intempestives (sqlite, conda blabla..)

**Comment by drosofff** [comment]
EUEeeeeeee...
Finalement c'est juste la version 1.2.1 du data_manager bowtie qui est buggée !!! 😄

**Comment by drosofff** [comment]
Je ferme donc ce problème @slecrom !

**Comment by slecrom** [comment]
Merci pour ton aide @drosofff. Est-ce que je dois réinstaller toute la VM pour faire la mise à jour ou je peux le faire via les outils install de l'admin ?

**Comment by drosofff** [comment]
interface admin, install/uninstall tools. tu désinstalles le data manager 1.2.1 et tu clique sur l'installation de la version précédente !

**Comment by slecrom** [comment]
Merci @drosofff j'ai installé la version 1.2.0 et l'indexation a fonctionné.
