### ISSUE TITLE
Jobs bloqués sur la nouvelle VM Galaxy

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#44]
@drosofff 

Je viens de relancer le TP pour tester la dernière version et j'ai un problème, mes fastqc ne se lancent pas. Ils sont en attente depuis 15' alors que cela marche d'habitude en 2'.

![Capture d’écran 2024-11-20 à 11 43 59](https://github.com/user-attachments/assets/8e758132-b9e4-4331-87d7-3b007c2294d8)

Peux-tu m'aider ?

**Comment by drosofff** [comment]
Oui ! **Donne moi vite le numéro d'IP de ta machine** !
J'ai encore fait un changement de code essentiel hier soir. Quand a tu déployé ta VM ?

**Comment by slecrom** [comment]
J'ai déployé la VM hier matin. Elle est accessible ici http://34.65.199.56/ Tu veux le MDP admin ? Je te l'envoies par SMS si tu veux ?

**Comment by slecrom** [comment]
J'ai lancé un clip adapter qui a marché

![Capture d’écran 2024-11-20 à 11 55 49](https://github.com/user-attachments/assets/1f8309d0-dca6-414a-a0e0-dd1b7ed771db)

**Comment by slecrom** [comment]
Est-ce que tu as changé les versions d'outils aussi ? Mon workflow de nettoyage ne marche plus non plus :-(

![Capture d’écran 2024-11-20 à 11 58 10](https://github.com/user-attachments/assets/6ee90ddc-f84b-46f0-9371-c0f80a2bc4a6)

**Comment by drosofff** [comment]
Keep cool... J'ai tout ce qu'il me faut. Je vais fixer celà ;-)

**Comment by slecrom** [comment]
Par contre dans 1 heure je dois partir et je vais suspendre la VM pour ne pas quelle tourne dans le vide tout l'après-midi.

**Comment by drosofff** [comment]
Laisse moi intervenir ! Un après midi de cette VM, ce n'est rien du tout !

**Comment by drosofff** [comment]
Mais ce sera réparé dans une heure de toute façon...

**Comment by drosofff** [comment]
#### Alors

Petit cachotier,

Ta VM a été déployée il y a plus de 12 heures, car je vois que la version de galaxyXpand est : 
```
commit 3347b4c6434a3312d247800641bde1709de0a722 (HEAD -> ag2024, origin/ag2024)
Author: drosofff <drosofff@gmail.com>
Date:   Mon Nov 18 19:54:37 2024 +0100
```

Je peux te proposer deux solutions.

- [ ] Tu déploies une nouvelle VM qui aura la dernière version de galaxyXpand
- [ ] Je fais retourner ansible sur ta machine actuelle, et dans 10-15 min max, ça marchera...

**Comment by slecrom** [comment]
Je suis là jusqu'à 13h alors va pour la solution que tu as cochée :-)

**Comment by slecrom** [comment]
Cool merci. Et pour le workflow, sais-tu comment faire pour le problème de version ? Est-ce que l'on peut modifier une version d'outil dans un workflow ?

**Comment by drosofff** [comment]
> Et pour le workflow, sais-tu comment faire pour le problème de version ?

Le workflow de Julie ?

Je l'ai essayé, il n'y avait pas de soucis.

On peut revoir cela ? Tu me mets une url au fichier .ga ? Ou tu me dis quand tu me l'as envoyé pour que je le retrouve ?

**Comment by drosofff** [comment]
@slecrom  J'ai ouvert une issue avec un workflow révisé pour qu'il fonctionne de suite. J'y ai ajouté aussi le workflow que j'utiliserais si j'étais à votre place (turbo)

**Comment by slecrom** [comment]
Merci. Par contre, je ne trouve pas la nouvelle issue que tu as ouverte. Voici le lien vers le workflow : https://psilo.sorbonne-universite.fr/index.php/s/Kdm3_smallRNAseqData/download?path=%2F&files=Galaxy-Workflow-sRNA_clean-up.ga

**Comment by drosofff** [comment]
issue #45

**Comment by drosofff** [comment]
Before closing, just mentionning that this issue was due to a misconfiguration of slurm in the ansible playbook (galaxyXpand) fixed in this [commit](https://github.com/ARTbio/galaxyXpand/commit/9024d45ffa4d63abc7dfa5a213975adb2c5da2e6).

For the records...
