### ISSUE TITLE
featureCounts not found!

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#46]
Hi @drosofff 

I am testing the RNA step of the practical and when I want to use the featureCounts tool, I am unable to found it. However, the tool is installer. I even tried to uninstall and reinstall it without any success.
Do you have any idea of where the problem come from?
![Capture d’écran 2024-11-22 à 10 29 32](https://github.com/user-attachments/assets/e1e97503-0235-4f75-bc92-488a7fadb15c)

**Comment by drosofff** [comment]
Je peux avoir l'ip de ta machine stp (sur le slack) ?

**Comment by slecrom** [comment]
Je viens de te l'envoyer. Mis à part ça le reste du TP fonctionne.

**Comment by slecrom** [comment]
Problème de cache du navigateur résolu

**Comment by slecrom** [comment]
Bonsoir @drosofff 
J'ai voulu faire un nouveau test ce soir sur ma VM, mais j'ai eu un problème avec featureCounts. L'outil est bien disponible, mais quand je le lance cela ne fonctionne pas. J'ai essayé de désinstaller la version 2.0.6 pour installer la version 2.0.3, mais j'ai eu le même problème.
Est-ce que tu peux me dire comment résoudre ce dysfonctionnement, car j'ai peur que le souci se présente la semaine prochaine sur les VM des étudiants également.
Je te remercie
Bonne soirée
![Capture d’écran 2024-11-27 à 20 53 16](https://github.com/user-attachments/assets/bb2124aa-89c1-47e2-ae24-bb9faec964a1)

**Comment by drosofff** [comment]
C'est probablement un problème de dépendance conda (This tool was disabled before...).
Le hic, c'est que je n'ai pas ce problème sur mes instances, c'est donc de la réparation "personnalisée".
Il faut que je puisse accéder à ta VM. Cela peut être réparé soit avec le menu "manage dependencies" qui peut être un peu retort à manipuler, soit en intervenant directement dans l'environnement conda dans galaxy/database/dependencies/_conda/envs/ . Au doigt mouillé ça devrait passer sans trop de problème via l'interface admin de Galaxy, car featurecounts n'est pas connu comme un outils à problème.

Conclusion: si tu peux laisser ta VM allumée demain à partir de 10h, j'aurai une petite heure pour regarder, cela devrait suffire. (et me donner l'ip externe de la VM).
Bonne soirée @slecrom

**Comment by slecrom** [comment]
Mon problème, c'est que la VM en question est celle qui a planté. J'en relance une autre pour voir si je reproduis le problème et je te donnerai l'accès demain matin. Mais si tu as des idées, pourras-tu me les communiquer pour que je les donne aux étudiants si on a ce souci la semaine prochaine ? Merci

**Comment by slecrom** [comment]
Ce matin j'ai relancé une nouvelle VM suite au crash de la précédente. Trop cool les snapshots ! Et là aucun problème avec featureCounts !

**Comment by slecrom** [comment]
Bonjour @drosofff 
Tout c'est bien passé avec 300 Go. Tu avais raison, c'est un problème de taille. J'ai atteint 180 Go de données dans Galaxy. Ce qui est amusant c'est que l'instantané ne prend que 75 Go. Cela fait une grosse différence !
Merci encore pour ton aide
Bonne journée,
Stéphane

![Instantanés](https://github.com/user-attachments/assets/6d47aff8-0c89-4b00-8bf3-a320c563bd21)
