### ISSUE TITLE
Plantage complet du serveur Galaxy

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#48]
Bonjour @drosofff 

Ce matin, j'ai reproduit un comportement que j'avais détecté déjà avant-hier. Lorsque je lance un job sur un grand jeu de données, le serveur Galaxy et la VM plante complètement. Impossible de me connecter en SSH à la VM et au serveur Galaxy.
Je l'ai rencontré mardi quand j'ai lancé les 6 jobs Bowtie RNA-seq, mais il ne s'est pas renouvelé hier quand je l'ai lancé sur 3 échantillons sur une nouvelle VM. Cependant, il s'est produit à nouveau ce matin quand j'ai lancé l'étape "Clip adapter" sur les 6 échantillons sRNA à la fois.

Je dirais aux étudiants de ne pas lancer de job sur un grand nombre d'échantillons et on sauvegardera la machine régulièrement, mais c'est assez embêtant car on perd tout.

Stéphane

![Capture d’écran 2024-11-28 à 08 08 41](https://github.com/user-attachments/assets/d442477a-abba-4f66-81b5-9ec259aa6a5f)
![Capture d’écran 2024-11-28 à 09 08 47](https://github.com/user-attachments/assets/b097680a-b592-49ac-a84f-b943571391d5)
![Capture d’écran 2024-11-28 à 09 08 38](https://github.com/user-attachments/assets/d0ac70cf-6d96-4172-a827-a4d885fd2abe)

**Comment by drosofff** [comment]
Ok @slecrom je vais investiguer ça soigneusement car ce n'est effectivement pas possible. 

Ce que tu décris ressemble beaucoup à une saturation de la RAM.

Ça doit pouvoir se soigner, que tu sois le seul atteint, ou que ce soit génétique 😉

**Comment by slecrom** [comment]
Merci pour ton retour rassurant. C'est fou que la VM ne résiste pas à un plantage de RAM.

**Comment by drosofff** [comment]
OK, je commence à regarder. Je teste les situations que tu as décrites. Pour le moment, tout se passe bien, mais il faut attendre que je martirise suffisamment la VM...

In the meantime, je voudrais m'intéresser à la VM bloquée. Elle est bloquée bloquée ? J'espère que tu ne l'as pas trashée, je voudrais essayer de la récupérer...
Sauf si tu avais un snapshot de ladite VM, auquel cas on peut investiguer à partir de ce snapshot.

Dis-moi @slecrom

**Comment by drosofff** [comment]
Il y a une autre hypothèse triviale qu'on oublie toujours et qui peut provoquer allègrement le crash d'une VM @slecrom :

Est-ce que tu es sûr que ton disque n'était tout juste pas saturé ?

J'ai remarqué que 200G ça peut être trop juste si on se lâche sur les tests... Et là, sur une VM, c'est sûr que ça fait TILT dans 100% des cas...

**Comment by drosofff** [comment]
@slecrom, mon petit doigt me hurle que c'est un problème de saturation de disque et je n'arrive pas à le faire taire 😄

**Comment by slecrom** [comment]
Est-ce que serait possible à cause des étapes de décompression des fichiers ? Si c'est le cas, est-ce que l'on peut augmenter la taille d'un disque d'une VM une fois qu'elle est créée ?

**Comment by drosofff** [comment]
Oui, pas super simple à faire, mais ça se fait.

Avec beaucoup de complication si le disque est en crash (en gros il va falloir le faire monter sur une autre VM, l'étendre, le démonter, et le faire redémarrer comme disque-OS...). Bref, quand tu vois que quand il y a des instructions à 2 lignes, ~10% des opérateurs vont oublier la première, ça fait un peu freaker 😃 .

Mais si on fait ça avant que le disque soit plein, je pense que c'est très faisable (mais il faut bien suivre le protocole).

**Comment by drosofff** [comment]
Je viens de reproduire ton crash en saturant le disque ! Je parie donc très gros que c'est le problème.
Par ailleurs @slecrom , je pense également que tes problèmes avec featurecounts été liés à ce problème, une sorte d'avertissement sans frais...

Mais, si on en revient au fond, il y a deux choses.

- Ce n'est pas vraiment la décompression "en background" le problème. Le problème, c'est que bowtie (1) ait besoin d'une part de décompresser les fastq et d'autre part que son output soit un sam et pas un bam...
- Est-ce que les étudiants vont vraiment être impactés dans la mesure où, en suivant les instructions, ils restent très en dessous des 200 G permis au total ?

Par ailleurs, l'oeuf de Colon dans cette histoire, c'est déployer un disque de 300G !

**Comment by drosofff** [comment]
@slecrom 

### Ultimate solution found !

1. Stop your VM
2. Make a snapshot of your VM
3. Deploy a new VM from this snapshot, taking care to choose a 300 GB disk (this is done through the VM setup menu).
4. Enjoy a new server with 300 GB capacity !

**Comment by slecrom** [comment]
Génial :+1: :fire: ça marche, j'ai tout récupéré dans une VM de 300 Go. Les snapshots c'est magnifique.

**Comment by drosofff** [comment]
⚠️ l'addiction au cloud computing peut nuire à vos proches ⚠️ 
Parlez-en au cloud-info-service, 01 44 27 70 05 😆
