### ISSUE TITLE
Durée de mapping 3x plus longue cette année

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#5]
Je viens de lancer l'étape de mapping avec l'outil "Map with Bowtie for Illumina" comme l'année dernière. Mais cette année, le mapping des 2 collections SF et WT lancées en même temps a pris 1h20 contre 30' l'année dernière. Si je regarde chaque échantillon, le mapping va de 33' à 1h alors que l'année dernière, on était plutôt dans les 15' en moyenne.

Pourtant, le lancement s'est bien fait en parallèle sur les 8 cœurs, je l'ai vérifié avec htop. Et j'ai bien décompressé les données en suivant ton tutoriel.

Si tu as une idée d'où cela peut provenir, je suis preneur, car là c'est trop long pour le TP.

**Comment by slecrom** [comment]
Trop bizarre. Je viens de relancer l'étape de mapping seule avec les mêmes paramètres sur un seul échantillon et le mapping n'a mis que 3' !

**Comment by drosofff** [comment]
Ca ne m'étonne pas du tout. Je n'ai pas le temps de regarder aujourd'hui, mais c'est typiquement un problème d'interférence entre cpu ce que tu décris. Je n'anticipe pas top de problèmes ne t'inquiète pas

**Comment by slecrom** [comment]
D'accord je suis rassuré. Du coup le mieux est de ne pas lancer le mapping par collection alors ? Ou alors de ne pas lancer les 2 collections WT et SF en même temps ?

**Comment by drosofff** [comment]
Sans toucher aux réglages de l'instance, j'ai fait deux runs sur la collection WT (3 alignements concurrents qui abondent tous aux 6 cpu) et observé les valeurs suivantes.

Du coup je ne suis pas sûr de ce qu'il faut faire car je trouve cela assez optimisé.

Je ne sais pas de quand date ton instance, mais j'ai fait pas mal de petits ajustements technique depuis une semaine. Il faudrait peut-être que tu retestes une instance "fraîche" ?

## run 1
```
Cores Allocated | 6
-- | --
Job Start Time | 2022-11-17 18:04:28
Job End Time | 2022-11-17 18:13:11
Job Runtime (Wall Clock) | 8 minutes
``` 



## run 2
```
Cores Allocated | 6
Job Start Time | 2022-11-17 18:24:41
Job End Time | 2022-11-17 18:36:14
Job Runtime (Wall Clock) | 11 minutes
```

**Comment by drosofff** [comment]
Bon, j'ai tunné un peu les jobs bowtie, maintenant ça prendra 1 minutes par dataset, qui passeront 1 par 1 (pas la peine de lâcher les collections, ce n'est pas à l'utilisateur de gérer le job scheduling !).

Du coup, c'est beaucoup mieux que l'année dernière ? ;-)

**Comment by slecrom** [comment]
Ok merci. Donc je recommence une installation propre de la VM ? Ou je peux faire une mise à jour de l'actuelle ?

**Comment by slecrom** [comment]
Je viens de relancer le mapping avec la nouvelle VM et cela a fonctionné en 2-3 minutes par mapping sans interférences. Merci.
