### ISSUE TITLE
L'outil "Filter SAM or BAM" ne fonctionne pas

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#6]
J'ai voulu utiliser l'outil "Filter SAM or BAM" pour supprimer de la sortie les lectures qui ne se sont pas alignées mais comme l'année dernière l'outil affiche un message d'erreur.

```
An error occurred while running the tool toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.8+galaxy1.
Fatal error: Exit code 127 ()
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

Je sais que tu avais fait un patch l'année dernière. Sais-tu où il se trouve ? Merci.

**Comment by slecrom** [comment]
Bon j'ai voulu en essayer un autre qui avait bien marché l'année dernière : FilterSamReads. Mais il n'est pas passé à Galaxy2 visiblement.

**Comment by drosofff** [comment]
### Use sambamba

aussi simple (voir plus) que samtools view, et notoirement plus rapide.
Je l'ajoute à la liste des outils et je configure son job
