### ISSUE TITLE
Comment arrêter le serveur Galaxy ?

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#7]
Je viens de lancer l'installation du serveur Galaxy sur une nouvelle VM avec le dernier script de déploiement. Je l'ai fait à Pasteur et je me suis déconnecté de la console.
Arrivé à l'ENS, je me suis reconnecter à la console, mais je n'ai pas vu de screen en train de tourner sur la machine.

Comment arrête-t-on la VM maintenant ?

**Comment by drosofff** [comment]
On arrête plus la VM, on la suspend.
Avec le nouveau script de déploiement, 

- `galaxyctl status` te donne l'état du serveur galaxy
- `galaxyctl start` si d'aventure le serveur galaxy est down, mais cela ne devrait pas arriver.
- `galaxyctl stop`pour arrêter le serveur, mais il n'y a aucun raison de le faire
- `galaxyclt restart` pour redémarrer le serveur, utile si besoin de mettre à jour des références, des changements de préférence, etc. Mais normalement pas utile pour ce TP

A noter que toutes ces commandes ne peuvent s'exécuter que dans le virtualenv de Galaxy (`(.venv)` visible dans le prompt de la console ssh). Mais cet environnement est activé automatiquement à la connexion ssh, donc il n'y a normalement pas à s'en préocupper.

Au redémarrage d'une VM suspendue, on retrouve Galaxy dans l'état où il était.

A noter cependant que si on suspend la VM **au milieu d'un job Galaxy en exécution** cela mettra le job en question en erreur (j'ai fait le test)
