### ISSUE TITLE
Collection petits ARN

### ISSUE THREAD

**Issue by slecrom** [ARTbio/AnalyseGenome#9]
Pour les petits ARN pas besoin de créer une collection avec les 4 jeux données, 103 et 105 suffisent pour le TP. Ils pourront utiliser les 2 autres s’ils veulent pendant le temps de travail personnel.

**Comment by drosofff** [comment]
OK c'est noté.

Pas besoin qu'ils les téléchargent non plus alors... Cette semaine je travaille sur la bande passante, et je chasse les traffics inutiles...
Rien n'empêche qu'ils les téléchargent à part quand ils veulent s'en servir

**Comment by slecrom** [comment]
Oui tu as raison.
